1)Hyr 25/09/2024
-------------
EXception Handling
------------------
1)Checkedxception(compile Exception ,file Exception,SQL Exception)
2)UncheckedException(Runtime -EXception)

->try{}
->Catch
->Finally
 
->Throwable
->Exception
->RuntimeException
>indexOutOfBoundsException
>NullPointerException
>ArithmeticException
->IOException
>FileNotFoundException
->SQLException


we want to print the Stacktrace()
->Arrays.toString(ae.getStackTrace()));

Exception Handling(2)
----------------------

->Try with resources
 -------------------
***which class implemented by the AutoClosable(interface)
we can use the those classes
1)it has initialization and declarization
2)and takes the semicolon(;) 
ex:
try(FileReader fr = new FileReader(file);
FileInputStream fis = new FileInputStream(file);
INputStreamReader isr = new InputStreamReader(fis);)

2)can we write the try with multiple catch blocks
--------------------------------------------------
a)yes
ex:
try{
int[] arr = {1,3};
}catch(FileNotFoundException e1){
e1.printStackTrace()
}catch(ArrayIndexOutOfBoundsException e2){
e2.printStrackTrace();
}
catch(ArithemeticException e3){
e3.printStackTrace();
}
3)can we wright the multiple exceptions in one single catch block
-----------------------------------------------------------------
a)yes
ex:
catch(ArrayIndexOutOfBoundsException | ArithemeticException | FileNotFoundException e)

4)Finally block execute the always in java?
--------------------------------------------
a)no 
System.exit(0); scenario it will not execute 

5)can we write the customException?
a)yes by using of throw new  key word 
ex:
try{
System.out.println(1/0);
}catch(ArithmeticException){
throw new ArithmeticExceptin("Stupid fellow" ,don't divide with Zero) 

6)can we write the user defined Exception
------------------------------------------
a)yes you can
ex:
package samplegvp;

public class HyrException {

	public static void main(String[] args) throws Throwable {
		try {
			System.out.println(1/0);
		}catch(ArithmeticException e) {
			throw new LoginException("login is failed please check the Exception");
		}
 }

}






















